apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meu-projeto
  name: meu-projeto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-projeto
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: meu-projeto
    spec:
      containers:
        - env:
            - name: SWAGGER_HOST
              value: 35.198.2.187
          image: gcr.io/validid-vpass-sandbox/meu-projeto:1.1.1
          imagePullPolicy: Always
          name: meu-container-node
          ports:
            - containerPort: 3000
