apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: meu-projeto
build:
  artifacts:
    - image: gcr.io/validid-vpass-sandbox/meu-projeto
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deployment.yaml
